apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-lustre-pv
spec:
  capacity:
    storage: 2400Gi  # Update to your FSxL FS size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-xxxx  # replace with your FSxL FS ID
    volumeAttributes:
      dnsname: fs-xxxx.fsx.us-east-2.amazonaws.com  # replace with your FSxL DNS name
      mountname: xxxx  # replace with your FSxL FS mount name
